### ISSUE TITLE
Improve Touch ID Security and Master Credentials Secure Storage

### ISSUE THREAD

**Issue by nicad** [strongbox-password-safe/Strongbox#128]
My Master password gets added to MacOS keychain if I use TouchID, I'm not sure why, it really shouldn't. Other applications like 1Password, Dashlane, KeePassXC don't behave this way and yet allow TouchID usage.

**Comment by mmcguill** [comment]
Hi @nicad, Yes, so this is why I have a big message/warning/caveat when using Touch ID on the mac (also on the iPhone btw) which looks like this:

<img width="426" alt="image" src="https://user-images.githubusercontent.com/344791/58765531-43b2c280-8574-11e9-9821-74323397b61d.png">

The reason the password is stored in the Keychain is that it has to be stored somewhere and that is the most secure place that it can be stored on the Mac. Unless you have some other suggestion or ideas?

So KeePassXC doesn't directly store your password in the Keychain, they store an AES Key/IV pair in the Keychain (look for "KeepassXC_TouchID_Keys_" for example) which is used to decrypt an in-memory copy of your password. This means that their Touch ID can not work at startup (you need to unlock your database with the manually entered password first). 

So there are differences between the two apps, yes, I personally want Touch ID to work as it currently does at startup no matter what. There may be some merit to doing some kind of simple encryption/obfuscation (basic XORing) before putting it in the Keychain so that someone with access to your keychain can't immediate see it, but by that stage you've already lost, a determined attacker would not have any difficultly decrypting/deobfuscating. If that's something you'd like to see please raise it as an issue.

If you are worried about your master password being stored in the Keychain, please as the warning suggests, do not use it. Hope all that makes sense.

**Comment by nicad** [comment]
Thank you for taking the time for this thorough explanation.

Do you know if 1Password or other similar products take the same approach than KeePassXC ? The ones I checked don't have the password in clear in the KeyChain but not sure if it's a temporary token or just obscured password. So I do think the keychain is the place to store this info, just not something equivalent to the master password, a temporary token seems a much better approach balancing security and convenience.

Here are a few arguments against the current behavior:
* All enterprise systems I've used as well as Apple devices and services have me re-enter my password when I restart a device. I think that's an ok trade-of, I wouldn't expect TouchID to work after a reboot (because Apple uses it this way) and don't mind entering my master password in that case. Devices reboot very rarely.
* even when StrongBox is not running my master password stays there. That's a big concern. My master password is the most important secret I have. It cannot stay in-memory or on disk when I shutdown the StrongBox app or turn off my computer. This increases the risk surface significantly.
* other password tool typical provide a way to specify how long to allow touchID. I think it's a good thing: (1) it should always be temporary (2) re-prompting for master password regularly is a good idea to not forget it. I haven't verified but I hope that once the time limit expires it's not possible to use what's in the keychain to unlock anymore (any security audit would not let that go I would assume).
* TouchID is mostly to speed up repeated actions IMHO, I tend to have burst of activity where passwords are needed and being able to control auto-lock delay and touchID interval helps me find the security/usability trade-of I'm willing to take.
* I don't consider the fake finger print scenario to be very likely but again having a time limit to the touchID unlock reduces the time someone can make use of it

That's my arguments for the behavior to change and be timed based with optionally the option to keep the password in the keychain forever.

**Comment by mmcguill** [comment]
Thanks @nicad for the thoughtful critique. I think this would be a good addition to the feature set and I'll add it to the list, and let's use this issue to track.

Desired Features:

- Obfuscated Master Password in Keychain
- Option to Request Master Password after App Restart (Should be Default)

I'm afraid I don't know how 1Password works (it's not open source) but very likely via Keychain as it's the most secure place you can store a secret like this on the device.

**Comment by mitchcapper** [comment]
Instead of storing the master password generate a random strong shared key and encrypt the master password with this key.   Store the shared key in the keychain.   That way just pulling the key from the keychain is not enough you must also get the encrypted file stored locally containing the master password.

To require the master password after app restart rather than storing in a file locally keep the encrypted blob in memory and not written to disk.   

They shared key could be regenerated each startup as well further preventing a formerly stolen keechain entry from being used on the current database (attack would need to occour at the same time).

There are more complex options as well (using the keychain data as a key to decrypt the master password using the security enclave).  I think this would be somewhat more straight forward to implement however than adding the public/private encryption reqs of the security enclave. 

At first it may seem like storing the encrypted master password in a file would be a big security weakness.   Keep in mind however as long as its encrypted using sufficient rounds and a secure random shared key someone having it can't really do anything only if they were able to compromise the shared key from the key chain at the same time.   Setting security to be at least equal to the original solution in worst case scenario.

**Comment by mmcguill** [comment]
Thanks @mitchcapper. Yes interesting idea... 

This is an improvement in security because rather than use the same key (say hardcoded into the App) you could use a different one on every launch (or even more often) and for every database, randomly generated. When you say "shared key" I presume you just mean a random key (& IV) stored in the Keychain.

So to be clear, the requirements for this feature then become:

1) Store a random encryption Key & IV in the Keychain
2) Use this Key/IV pair to encrypt the Convenience Master Credentials (Password and Key File Digest)
3) The encryption process should be computationally intensive (say 20,000,000 rounds of AES256 in CBC mode) to make brute force unfeasible even if you managed to get the encrypted blob.
4) Store this in:
     - a) App Memory Only (Default) - Requires Manual Entry on App Restart
     - b) Durable Storage (This is probably easiest to store in NSUserDefaults rather than a simple file).
5) For 4b) change the key/iv on each app launch to reduce surface area for attack
6) Relevant Configuration for above

This would be a great improvement over the current setup. Thanks for the input!

**Comment by mitchcapper** [comment]
Much more eloquently put.   You also don't need to overkill the round count (as long as your random key is just random bytes as its not a normal password being bruted).  I would say its likely an un-needed precaution but as the key is virtually never wrong as long as it completes in a responsive time (say under a second) doesn't hurt.

GL:)

**Comment by hcksw** [comment]
Hi Mark,

I just read the above and wondered if you are aware of this support page from 1Password which explains how they store keys in the keychain. 
https://support.1password.com/touch-id-security-ios/
https://support.1password.com/touch-id-security-mac/

It seems they use a particular attribute setting so that iOS automatically deletes what’s stored in the keychain after a reboot. It also has other security advantages (no backups etc.)

If I’m misinterpreting the issue above, then apologies. 

Alan

**Comment by mmcguill** [comment]
I hadn't seen those, and they look good and reasonably comprehensive. This is something I think can be looked at at the same time as the above suggested changes. Thanks for the extra info @hcksw

**Comment by mmcguill** [comment]
This is now available as of Mac 1.45.6 & iOS 1.45.8. It's a completely new module I've written to manage these secrets. It uses the same technology as mentioned in the 1Password links above.

That is it uses the Secure Enclave (when available, otherwise it will fallback on the keychain). Importantly for Mac users, the master password is no longer stored unencrypted in the Keychain... The new module also supports expiry and in memory storage only which makes the implementation of expiry on restart or at a fixed period much easier to implement in the future... 

You can read more about the details of how the system works in the FAQ I've written up here:

https://strongboxsafe.com/hrf_faq/how-does-strongbox-securely-store-confidential-information-e-g-master-passwords-sftp-webdav-credentials-is-it-secure/

I'm going to close this one out soon, but will leave open for comments for a short while...

**Comment by mmcguill** [comment]
Closing as this seems to be working reasonably well (i.e. no flood of issues/complaints)... will remove SAMKeychain/JNKeychain in a few months entirely from the project when everyone has migrated from old system.
