### ISSUE TITLE
Dropbox: Reduced API permissions - App folder only access

### ISSUE THREAD

**Issue by define-null** [strongbox-password-safe/Strongbox#134]
It would be great to have an option to grant stongbox only App Folder access while connecting to dropbox.

**Comment by mmcguill** [comment]
Hi @define-null do you know if the API supports this?

**Comment by define-null** [comment]
Yes, https://www.dropbox.com/developers/reference/developer-guide#app-permissions
I also know, that keepass2android project https://github.com/PhilippC/keepass2android/ has this feature in place.

**Comment by mmcguill** [comment]
Right, ok thanks. The issues here are:

- People may want to store their databases anywhere in the hierarchy
- People having been using the app for years now, and will not be using the particular Strongbox App Folder if I were to create that

This would mean breaking current users setup if I were to reduce the permissions currently, and would require some changes. 

I don't hate the idea, but originally I just wanted it to work out of the box for most people rather than have to explain/point at a particular folder if they wanted to use it.

Perhaps this could be solved by having 2 Dropbox providers (stricter & looser permissions) on the Screen, or asking the user which one they'd like to use if they select Dropbox.

One way around this is to use Dropbox via the iOS Files app, you can open/Edit In Place from Files, or Add via iOS Files in Strongbox itself and this way Strongbox does not have any direct access to Dropbox at all. 

Hope that makes sense?

So while possible, the impact to existing users and the availability of a reasonable workaround for those worried about API access make this issue would unfortunately a low priority for development.

**Comment by define-null** [comment]
Thanks for the response. I understand and agree with your intent to keep backwards-compatibility, and I didn't mean to break it, but rather was suggesting to provide another type of connection. 

> Perhaps this could be solved by having 2 Dropbox providers (stricter & looser permissions) on the Screen, or asking the user which one they'd like to use if they select Dropbox.

In case of keepass2android if offers two storage types called "Dropbox" and "Dropbox (folder KP2A)" and if I remember correctly it shows a info message that briefly describes what kind of permissions this type of storage provider requests. 

While using the password manager already imply a certain level of trust it would be really nice to have an ability to restrict it's access to the reasonable minimum, especially if there is a lot of stuff under the dropbox account in which case having whole copy on the phone and using the trick that you described might not be achievable. Plus allowing just another app to potentially mess with your whole dropbox data might not be desirable, though I understand why this request might not be in the high prior)

**Comment by mmcguill** [comment]
Understood. Thank you for the detailed reply.

How do you feel about using the alternative using iOS Files method (no permissions for Strongbox required)?

**Comment by define-null** [comment]
I haven't tested the latest dropbox app version, but I'm not sure that it allows to keep only single file out of the whole account in sync with the phone. Without sync with pc I don't need a password manager on the phone otherwise )
Anyway thanks for your suggestion, I will look for workarounds

**Comment by mmcguill** [comment]
Ok, understood. Didn't know that, thanks for the info.

**Comment by zahidmak** [comment]
Is there any plan to roll out this feature? I recently moved to Keepass and it would be great to have reduced dropbox permission for iOS. Keepass port on Android "Keepass2Android" has this feature. Thank you for the amazing app.

**Comment by mmcguill** [comment]
Hi @zahidmak thanks for the App Love. It's still on the list but it's just a matter of scheduling. I'll try bumping up the list a little

**Comment by SudoMike** [comment]
One point I'll add against the iOS Files app is that it's even worse than giving full access to Dropbox because iOS has no granular control over which of your files an app can access. If you grant an app access to Files, it has access to your whole Dropbox + local files + iCloud files.

**Comment by strongbox-mark** [comment]
I've spoken with @SudoMike separately by email about this. But just to re-assure any others, the above comment is incorrect, the Files method only allows access to a single file which must be picked/selected by the user interactively. Strongbox has no way to know where it is, etc. It only gets an opaque "bookmark" to that file.

**Comment by strongbox-mark** [comment]
Hi @define-null @SudoMike and @zahidmak, with the release of 1.52.23, you can now choose to use Dropbox in restricted "App Folder" only mode.

To switch this on:

Preferences > Advanced > Miscellaneous > Use Dropbox App Folder Only.

You should also clear any existing Dropbox sessions as they will no longer be  valid. You can do so like this:

Preferences > Cloud > Manage Cloud Provider Sessions > Unlink Dropbox.

Now you can add Dropbox databases, but only from the official Strongbox folder. 

Any feedback welcome (comment here, or drop an email to support@strongboxsafe.com)...

Cheers,
-Mark
