### ISSUE TITLE
Optional Auto Fill Unlock Timeout [within auto-lock timeout]

### ISSUE THREAD

**Issue by jtkohl** [strongbox-password-safe/Strongbox#150]
In the iOS app, there's a preference for "database automatic locking" when you switch away from Strongbox.
I want this same delay to apply to password-filling inside another app, such as safari logins.
Use case:
* open a page in Safari that needs a login
* tap on passwords button
* select strongbox as source of passwords
* type in password for default database
* select the desired username and password
* those are filled into the application, and I can proceed
* moments later, open another app or a new web page that needs a different username/password
* tap passwords button
* select strongbox
* <<< I am prompted for database password again...here's where I want the previously opened database to remain open, until the auto-lock delay has passed >>>

**Comment by mmcguill** [comment]
Hi @jtkohl, this is technically possible, but because the AutoFill extension is launched as a brand new process on each launch, it would mean that Strongbox would need to know your Master Password (which it does if you use a convenience Unlock method (Biometric or PIN Code) and use it to auto unlock your database.

This would mean when launched Strongbox could check the last launch time, compare it with the timeout, if ok, then open your database automatically using those stored credentials.

I don't know how comfortable you/others would feel about this auto opening? 

I suppose if this is an opt-in preference with a warning when enabled, this would be acceptable to most?

**Comment by jtkohl** [comment]
Oh shoot, I was suspicious the system design was something like this (new process every time, rather than reusing an existing running application).
Perhaps you could set up the "real" app as a local service, and have the autofill extension connect to it/query it for a cached password?  (similar idea to how macOS KeePass XC browser extension talks to KeePass XC as a local service)

**Comment by mmcguill** [comment]
Yeah, that's how it works alright. 

With regards to setting up some king of service, there are two main problems there:

1) Keeping the application running in the background is hard to do, iOS usually terminates/snoozes them after 2-3 minutes
2) Interprocess communication would be difficult, and also probably prone to security issues.

I'd say the first method of automatically opening the database is much preferable from a development point of view for sure. Less prone to bugs, smaller workload, and same result.

**Comment by strongbox-mark** [comment]
This is now available as AutoFIll Convenience Auto Unlock with 1.52.8.
