### ISSUE TITLE
Hide info on iOS app switcher only when app/database is locked.

### ISSUE THREAD

**Issue by SuperTachyon** [strongbox-password-safe/Strongbox#167]

**Comment by mmcguill** [comment]
Thanks @SuperTachyon. 

I presume you mean hide info on that App Switcher screen only when the database is unlocked? (Browse, Item Details Screens (& Child Views)).

Otherwise, you're happy with say the Databases List or the App Preferences screens being visible on the App Switcher preview?

**Comment by SuperTachyon** [comment]
I actually do mean when it’s locked. I would prefer it showing a normal thumbnail like other apps, unless the app/database is locked.

**Comment by mmcguill** [comment]
Right, when it's locked you don't want to hide it, it should be visible. 

To be clear, you want:

- Databases List: Standard Thumbnail (Do Not Hide)
- Quick Launch View: Standard Thumbnail (Do Not Hide)
- App Preferences View: Standard Thumbnail (Do Not Hide)

But

- Browse View (Folders, Entries, TOTP List) - Privacy Screen Thumbnail (Hide)
- Item Details - Privacy Screen Thumbnail (Hide)
- Sub/Child Screens of the above (Database Management, Sort Order, View Preferences, etc) -  - Privacy Screen Thumbnail (Hide)

Does that sound right?

**Comment by SuperTachyon** [comment]
I think we’re having some misunderstanding here. I’m coming from 1Password and preferring its behaviour in terms of thumbnail in App Switcher. 

The behaviour I’m suggesting is the following:

1. If we’re not in a database, 
    (a) show the blank blue screen if the app is locked
    (b) show normal thumbnail if the app is not locked
2. If we’re in a database,
    (a) show the blank blue screen if the database or app is locked
    (b) show normal thumbnail if the database or app is not locked

I’m not sure if that makes sense.

**Comment by mmcguill** [comment]
Ok, yes, think I see what you mean. Let me try break down your scenarios.

Firstly, I'd like to note that the state of "Database Locked" and being "In a Database" are mutually exclusive and we can therefore simplify section 2s requirements to:

1. If we’re not in a database:
    (a) show the blank blue screen if the app is locked
    (b) show normal thumbnail if the app is not locked
1. If we’re in a database,
    (a) show the blank blue screen if the app is locked
    (b) show normal thumbnail if app is not locked

Sections 1 & 2 become identical and can be stated as:

- show the blank blue screen if the app is locked otherwise show the normal iOS thumbnail

The key change then becomes:

- Show the standard iOS normal thumbnail if app is not locked

There is an issue here around delayed locking (app and database). So one can set a delay on either, and I need to investigate if it's possible to change the iOS Thumbnail in the background (say after the 2 minute delay)... I believe back a few releases ago say, iOS 10 I think, this wasn't feasible as iOS took a bitmap screen capture and that was that, no way to change it. I think this has changed.

Anyway, hope that makes sense, let me know if you disagree with any of the above.

**Comment by SuperTachyon** [comment]
If it’s hard to change the thumbnail after a certain delay, it’d be nice to have the option to always use normal thumbnail.

**Comment by mmcguill** [comment]
Ok, understood, maybe an option like (Always, When Locked, Never)

**Comment by SuperTachyon** [comment]
I compared the behaviour of 1Password and Strongbox more closely. One distinction is that when invoking app switcher in the app, Strongbox immediately becomes a blank blue screen (of death), while 1Password retains the same interface with normal thumbnail. 1Password only goes to the blank thumbnail when we actually switch away from the app, i.e., when switched to another app or went to home screen. 

It is Strongbox’s abrupt translation to blank screen when invoking app switcher that makes the experience feel not as smooth and polished.

**Comment by mmcguill** [comment]
Understood @SuperTachyon - Unfortunately takes a lower priority to some other tasks on the Roadmap at the moment...

**Comment by SuperTachyon** [comment]
Well, it’s better late than never. At least the idea is not rejected like on the KeePassium side,

**Comment by mmcguill** [comment]
Ok, seems reasonable I think. Cheers.

**Comment by SuperTachyon** [comment]
Is this likely to be implemented in the near future? I’m trying to see if I should close it and move on.

**Comment by mmcguill** [comment]
Hi, it’s hard to give a good estimate here. The issue seems to me to be quite cosmetic and there  haven’t been any other requests for similar which is how I try to gauge priority. 

Is this a show stopper for you? When you say move on it sounds like it is? 

If you feel it’s an absolute requirement for your situation it is probably best to try find a more suitable solution which solves this problem for you already. 

Sorry that’s probably not ideally what you wanted to here but there are quite limited development resources available.

**Comment by SuperTachyon** [comment]
I understand the limited resources. 

I’m currently mainly using 1pw with my family. I’ve been trying strongbox and debating if I should move everything to strongbox for various reasons. 

Although the issue is purely cosmetic. Considering I’m using a more polished product with better cosmetics, and the move could be a demanding task, this has been a showstopper for me. I don’t feel like giving myself one other annoyance in the process.
