### ISSUE TITLE
Double Touch ID Request

### ISSUE THREAD

**Issue by mmcguill** [strongbox-password-safe/Strongbox#207]
It appears some users are experiencing double requests for Touch ID on Mac

**Comment by monovertex** [comment]
I am experiencing this on iOS and is highly annoying. The second touch ID prompt covers the first one and is successful, but then the first one fails and always prompts me to insert my password. Basically Touch ID is pretty much unusable right now, for me at least.

**Comment by mmcguill** [comment]
Are you using Quick Launch @monovertex?

**Comment by monovertex** [comment]
@mmcguill I was using it, but since the issue started I disabled it, to see if it would solve it, but the issue persists.

I also tried disabling Touch ID and re-enabling it. It's a bit weird, the bug doesn't always happen, I just tried it now and on the first try it prompted for Touch ID a single time and everything worked, but on the second time it was doubled again.

**Comment by Slummi** [comment]
This issue sounds a little bit like the iOS issue #195.

**Comment by mmcguill** [comment]
Yes sounds like it. We’ll see with iOS13.2

**Comment by mmcguill** [comment]
This should be fixed for you now, with overhaul for Apple Watch unlock... Please reopen if that's not the case
