### ISSUE TITLE
Offline Edit and Re-Sync Request

### ISSUE THREAD

**Issue by Stefan136** [strongbox-password-safe/Strongbox#230]
Hello,

I'm connecting Strongbox to my KeePass DB on a QNAP NAS using WebDAV interface.
This works very well when I'm connected to my local WLAN or via VPN remotely.

Without a network connection I can open the DB in Read-Only mode, which is fine if you only want to get a password.
However it isn't possible to add/edit an Entry when you are not able to connect to your local network.

Could you allow to edit/add new entries also in Offline Cache mode?

In this case, the DB could be updated via WebDAV, once you open Strongbox and the device is connected to the network again.

Many thanks :)

Stefan

**Comment by Slummi** [comment]
I understand your problem, but I think that an update of the database at a later time wouldn‘t be a good idea - at least not as long as we don‘t have the synchronization feature, which will prevent Stongbox from overwriting entries, which have been created or modified by another KeePass client in the meantime.

Slummi

**Comment by mmcguill** [comment]
Noted, I’m hoping to start work on Merge/Offline features soon...

**Comment by juanbretti** [comment]
This is very cool idea. Risky, but great idea.
Maybe should save the time-date of the original and before update/save at the WebDav the file... It should tell you that the online copy has been updated after you got the Offline cache.

**Comment by strongbox-mark** [comment]
This is now technically possible (AutoFill always works in Offline mode) though blocked from full implementation in the Main App because it is dependent on #17 (Sync/Merge feature mentioned above by @Slummi ) - That feature is on the way. Once that is available this will become possible.

To try to cleanup the issues here, we will track this issue under #50 - which is an earlier request for the same feature...
