### ISSUE TITLE
Drag and Drop on macOS is jumpy

### ISSUE THREAD

**Issue by pzb** [strongbox-password-safe/Strongbox#235]
If I have two databases open, trying to copy an entry by dragging from one to the other is very hard.  Whenever the cursor gets over the other tab, it starts jumping around.  Is is very hard to find the "magic" point at which it will show the other database to drop it.

**Comment by mmcguill** [comment]
Hi @pzb - I believe this is just standard Mac system behaviour, there's not much I can do from my side. 

One thing that might help is to drag the destination tab away from the tab bar, which will separate that tab into it's own window. It should be easier then to drag onto...

Another option which helps is to use Copy/Paste instead of Drag/Drop, so just Cmd+C from source, Cmd+V to destination

**Comment by mmcguill** [comment]
I don't think there's anything actionable here that can be done... closing out
