### ISSUE TITLE
Database automatic locking not working

### ISSUE THREAD

**Issue by dne** [strongbox-password-safe/Strongbox#237]
Automatic locking doesn't seem to work for me. To reproduce:

1. Open/unlock database.
2. Make sure database automatic locking is enabled, without delay.
3. Switch away from Strongbox (to home screen or other app).
4. Reopen/switch back to Strongbox, and the database is still unlocked!

I'm currently on Strongbox Pro 1.44.5 and iOS 3.2.3. The above behaviour applies both to local and iCloud databases.

**Comment by dne** [comment]
Hmm, it seems Strongbox had gotten into a weird state. After I quit and restarted it, the automatic locking started working properly.

**Comment by mmcguill** [comment]
Thanks for the report @dne - I've heard of this happening before once or twice, seems like there is some sequence of activation/deactivation that can get Strongbox into this state, but I haven't been able to figure out what it is yet and so I can't debug/fix... The solution as you've discovered is to kill Strongbox and restart

**Comment by mmcguill** [comment]
@dne Are you using Touch ID or Face ID in this situation? Received another report which was Touch ID based in #246

**Comment by milesmcclane** [comment]
Thanks @mmcguill. Not sure if this is useful, or what caused this, but I had just played about with one of my database encryption settings in another app (KeepassXC on a Mac), reducing the memory slightly for argon 2 and chacha20 based kbd4. (Still trying time get autofill iOS working properly, and it doesn’t seem possible to change or alter these settings with either strongbox for iOS or macOS as yet).  

Strongbox on the iPhone had trouble opening it database after this, and I had to delete and re add it to the app, and also obviously redo all my database specific settings within strongbox, such as pin codes etc. 

If the bug was a result of this, it should be mentioned that it affected the newly changed database, the other two unchanged databases and the app in general.

**Comment by dne** [comment]
@mmcguill Yes, I'm using Touch ID and, as @milesmcclane described, when Strongbox was in its "weird state", cancelling the Touch ID prompt let me bypass the lock/access the app.

FWIW, this hasn't occurred again since then though.

**Comment by mmcguill** [comment]
Thanks @dne - Yeah it's rare but some how something goes a little awry and Strongbox gets the state wrong

**Comment by mmcguill** [comment]
I believe this one is fixed now. There was an issue with the Lock Screen not being able to present itself in certain circumstances (nested UINavigationController presenting a modal) - when this happened Strongbox didn't realise the lock screen was not presented, leading to bad state and the lock screen not being presented again for the life of the process. This is taken account of now, and there is a little more defensive code to catch if the lock screen has trouble being presented.

**Comment by mmcguill** [comment]
Please re-open if you still experience this issue on latest build.
