### ISSUE TITLE
Unable to move an item from a group/folder to root

### ISSUE THREAD

**Issue by Ben-Voris** [strongbox-password-safe/Strongbox#249]
With Password safe format, I can move an item to an existing group by tapping on `Edit`, selecting an item, tapping on the folder icon, selecting a folder, and then tapping `Move Here`.

What I do not see is the ability to move an item to the root (not in any folder).

**Comment by mmcguill** [comment]
Hi @Ben-Voris - I can't reproduce this issue, or rather I can move an entry to the root folder. 

The steps I follow are

1) Unlock Database
2) Tap into a folder with an entry I will move
3) Tap Edit, Select the entry, Tap 'Move'
4) Move screen appears, and it's in the Root folder displaying the Folders in Root
5) I tap 'Move Here' 

The result is the item is moved to the Root folder.

Are you not seeing same? Or perhaps I'm misunderstanding the issue. 

If you could when opening issues, please provide the steps you've performed, any screenshots if possible so that I can reproduce the issues this side. It would be super helpful if you do this on a new dummy database too - meaning you could also share screenshots. Thanks!

**Comment by Ben-Voris** [comment]
II works. In my defense, I see no indication that the move would be to the root of the safe.
