### ISSUE TITLE
Make WebDAV Connection Configurations Reusable

### ISSUE THREAD

**Issue by vessev** [strongbox-password-safe/Strongbox#310]
Hi Mark and community,

i have multiple Password Files on my WebDAV Server from my Email Provider.

The URL String is quite long and i have to copy paste this URL string from one of my password entrys.
That means i neet to write down my User and Password for the WebDAV Login cause i can't use my password manager in my passwort manager ;)
Is it possibile to pre create an webdav connection entry in a separate menu section which can be used via dropdown etc. for an existing/new database?

This is just an optional request - this tool is awesome and i will support it no matter what. 

Best regards, Michele

**Comment by mmcguill** [comment]
Hi @vessev - Thanks for the suggestion, it's a good idea...

One thing that might help/mitigate this issue, you can use Auto Fill to fill in to the username/password so that you don't have to write it down somewhere. 

Does that not work for you?

**Comment by sindastra** [comment]
I too, wished for this feature for a long time now. I thought I'll say something, so this issue doesn't get forgotten.

As for the workaround, it's a bit tedious since you cannot autofill the URL, but you can also not use Strongbox to look at the database to get the URL while doing the setup of a WebDAV connection...

**Comment by strongbox-mark** [comment]
Hi all, this is now available with 1.53.0. SFTP and WebDAV configurations are editable, and re-usable. :) Please open new issues if you see anything wrong.
