### ISSUE TITLE
Enquiry about iOS Password Expiry/Keychain Security

### ISSUE THREAD

**Issue by hcksw** [strongbox-password-safe/Strongbox#326]
Hi Mark.

Firstly, Strongbox Password Safe is an excellent product, great work and I think the annual fee I pay is very good value.

One security observation related to issue “Improve Touch ID Security and Master Credentials Secure Storage #128” which you have closed. I understood that you had switched to a more secure keychain use that would delete the master password from the keychain on device restart, which is a standard security feature of 1Password, KeePassXC and many other password managers. This assumption was based on two facts: 1) You noted the following as a desired feature on 7 June 2019: “ Option to Request Master Password after App Restart (Should be Default)” and 2) you mentioned on 23 Jan 2020 after deploying the update: “ It uses the same technology as mentioned in the 1Password links above.”

However I have noticed that my FaceID continues to work without requiring the master password even after a full device restart on an iPad with iOS 13.4.1 and latest StrongBox (1.48.0). 

I’ve read through the issue post and your related FAQ entry on this again and I see that you are using the following constant: “kSecAttrAccessibleWhenUnlockedThisDeviceOnly”. The is not the same as “kSecAttrAccessibleWhenPasscodeSetThisDeviceOnly” as used by 1Password and others and which requires the Master Password to be reentered following a device restart. In Apple’s language the second constant above has the additional feature: “Disabling the device passcode causes all items in this class to be deleted.” I understand that this includes a device restart as well as other forms of disabling (wrong FaceID forcing the user to enter device password, holding down keys to force FaceID to be disabled etc.)

I can understand the rationale for the security constant you have chosen as it provides additional convenience by not deleting the master password during a restart and is still more secure that how Strongbox previously handled passwords, however I’m not sure it is consistent with what has been said in the issue discussion. Perhaps you can clarify if the security choice made was deliberate and you intended that the master password would not be wiped on restart (i.e. convenience over security) or if there has been some confusion and you would like to review the choice of constant.

Thanks!

**Comment by strongbox-mark** [comment]
Hi @hcksw, thanks for your kind words about the app.

Yes, ok, #128 covered a lot of ground, and I wasn't explicit about all the choices I made there. The core ideas that came out of it were

1. Use the Secure Enclave when available
2. Stop using third party libraries for the keychain functionality
3. Use the constants you mention above to avoid any kind of cloud backup and delete on passcode reset
4. Enable a kind of expiry (secret deleted at a certain point in time)
5. Extend this expiry into the UI (iOS and Mac) and configuration

As part of #128 we got 1,2 and 3 (though more on that below), 4, and 5 (on Mac only at the moment). So, there is still some work to be done and I think #128 was closed a little prematurely (my fault). With all of the requests and various features the issue became overloaded. From my point of view the most important thing was to move to the new more secure system of storage (1,2, 3, and 4). 

Extending the expiry (5) (at a point in time or on App Restart took last place these key technical enhancements). So what remains of 5 is to extend this configuration to iOS. One of the reasons this got delayed was because it was a key feature and I wanted to see how it panned out on the Mac (it's working ok, but not perfectly and I still need to investigate that). So this should be coming along in the medium term.

To your point about the security keychain constants. This I do need to look at, but I do think you may not have the right understanding here... When you say:

> The is not the same as “kSecAttrAccessibleWhenPasscodeSetThisDeviceOnly” as used by 1Password and others and which requires the **Master Password** to be reentered following a device restart.

You are referring here to the Master Password of the KeePass database I assume? This is not what the "Passcode" refers to in the above constant, the Passcode refers to the device passcode (usually 6 digits). The master password reentry feature would be built on top of something like the current Secure/Secret store and would be orthogonal/unrelated to this constant. 

So the difference between the 2 constants is the requirement for the device to have its **device passcode** set only. While this seems minor, I think you (and 1Password) are probably right that it should be the default. I believe the reasoning behind originally choosing this was because I didn't want to exclude people who don't set their device passcodes from being able to using Face/Touch ID to unlock. I think this is probably a super marginal group of people (is it even possible to not set your device passcodes on iOS these days?). Effectively we're looking at a very slight difference but it's definitely worth fixing I think. 

So thanks for raising...

**Action Items**
- Make Convenience Password storage expiry accessible through the UI on iOS
- Use kSecAttrAccessibleWhenPasscodeSetThisDeviceOnly as the default

I will create two Github issues for the above and we can continue tracking from there...

**Comment by hcksw** [comment]
Thanks for the comprehensive answer Mark.

Yes, you’re right I am mixing up device password and the KeePass database master passwords. I thought there was some connection here, ie if Strongbox stores a master password in the keychain with those settings then whenever the device password needed to be reinput the master password stored in the keychain and requiring FaceID would be erased but actually that does not seem to be how 1Password works. It requires a reboot to be reset or a change in password or after a set expiry time. I imagine there are some additional steps they have to achieve this.

Also, if it’s of interest ProtonMail have written about these constants also on their blog as they use something called AppKey protection to store password using keypairs I believe. Their iOS app is open source and on Github so you can investigate the code if something looks interesting. 

https://protonmail.com/blog/ios-security-model/
https://protonmail.com/blog/ios-security-recommendations/

Looking forward to following the updates on here and appreciate it will take time.

Thanks again!

**Comment by strongbox-mark** [comment]
Thanks for those links, they’re a good read. Yep, stay tuned for updates.

**Comment by strongbox-mark** [comment]
I believe we can close this out now as remaining issues have been split out and the large majority of this work is done.

**Comment by Kagami** [comment]
Hi, @strongbox-mark, could you please clarify regarding the

> 4. Enable a kind of expiry (secret deleted at a certain point in time)

Also I found in the FAQ on the site:

> It is within the realm of possibilities that someone with access to your device and your fingerprint or photo, can produce a good enough fake to fool Apple’s system. Therefore you should be aware that a strong passphrase held only in your mind provides the most secure experience with Strongbox.

Am I correct that these counter measurements are only needed for the people who are afraid of TouchID/FaceID vulnerabilities?

As far as I understand there are no known ways to compromise keys/cryptography inside the Secure Enclave so if you assume that attacker can't fake your photo, you can store key for KeePass master password encryption inside Secure Enclave without expiration, i.e. forever and it won't cause any security issues?

**Comment by strongbox-mark** [comment]
HI @Kagami - Yes, your understanding is correct. As far as I am aware there are no known ways to compromise the Secure Enclave.

The warning is aimed at Touch/Face ID, which I believe (for Touch ID at least) there was a fairly sophisticated way to fool the sensor

So, the warning is just there to be upfront with people. It's hard to beat a password stored only in your mind in terms of security. But for convenience, it's hard to beat Face ID... As always a trade off is required based on your threat model.

Hope that makes sense.

**Comment by Kagami** [comment]
Got it, thanks. Another suggestion might be to use PIN instead of FaceID (6 digits shouldn't be easy to brute force because of timeouts) or enable auto-delete feature assuming attacker can't fake your FaceID with just few attempts.
