### ISSUE TITLE
OS based custom URL handle/URL overrides

### ISSUE THREAD

**Issue by Niko-CZ** [strongbox-password-safe/Strongbox#415]
Hello Strongbox team,
I would like to request one feature which will be really much useful for multi-platform teams working on MacOS, WIN and sharing same password DB.
In Windows Keepass app double click can be handled by "URL overrides", so definition could be:
ssh1 --> cmd://putty.exe -X -l -ssh {URL:RMVSCM} 
chrome --> cmd://{GOOGLECHROME} {URL:RMVSCM}
making URLs in the form of:
  - ssh1://myhost.local.net -l oracle -pw passwd -loghost "myhost"
  - chrome://http://google.com
  - sapgui://host.domain.com 77 -client=000 -user=DDIC -pw=password
these URLs can be handled with self-written script in Mac OS, which is opening them in configured app.

Is it possible to react in Strongbox on URL double click with following logic:
open '<URL>'
,where [open] is regular terminal command. So all the mentioned commands will be substituted:
- open 'ssh1://myhost.local.net -l oracle -pw passwd -loghost "myhost"'
- open 'http://google.com'
- open 'sapgui://host.domain.com 77 -client=000 -user=DDIC -pw=password'
?
Or create similar to "URL overrides" option in the app, so we will be able to re-define logic without changing of URLs?

I'm ready to pay for such option as part of "premium" paid version.

Regards,
Nikolay

**Comment by strongbox-mark** [comment]
Hi Nikolay, thanks for the feature request, sounds like an interesting addition - I'm not familiar with URL overrides but we can consider this ticket a research request. I would advise you however that it is well done the development backlog.

This is a Mac feature request, right?

**Comment by Niko-CZ** [comment]
Hi Mark,
yes this request is for Mac OS.
I know a lot of IT people using URL field for launching of application based on the '<URL>://' string on Win/Linux, what makes the kdbx management tool really powerful. For Mac such behavior may be found in MacPass (<=v 0.7.3).
In fact any app which has command line interface can be automated for launch-on-click logic. F.e. for Windows: Putty, WinSCP, PuttLink, etc.
>>I'm not familiar with URL overrides
In KeePass (WIN) you may find this option [Tools]-->[Options...]-->[Integration]-->[URL Overrides...]. It gives great flexibility to interpret URL string based on personal requirements or simplify it (in case of same long template used in all strings). F.e.:
[sapgui://] --> [cmd://sapshcut.exe -maxgui -system=XXX -language=EN -guiparm={URL:RMVSCM}]
So final string will be [sapgui://host.domain.com 77 -client=000 -user=DDIC -pw=password] and "language", "system" properties will be implicitly defined.

**Comment by khemstad** [comment]
> Hi Mark,
> yes this request is for Mac OS.
> I know a lot of IT people using URL field for launching of application based on the '://' string on Win/Linux, what makes the kdbx management tool really powerful. For Mac such behavior may be found in MacPass (<=v 0.7.3).
> In fact any app which has command line interface can be automated for launch-on-click logic. F.e. for Windows: Putty, WinSCP, PuttLink, etc.
> 
> > > I'm not familiar with URL overrides
> 
> In KeePass (WIN) you may find this option [Tools]-->[Options...]-->[Integration]-->[URL Overrides...]. It gives great flexibility to interpret URL string based on personal requirements or simplify it (in case of same long template used in all strings). F.e.:
> [sapgui://] --> [cmd://sapshcut.exe -maxgui -system=XXX -language=EN -guiparm={URL:RMVSCM}]
> So final string will be [sapgui://host.domain.com 77 -client=000 -user=DDIC -pw=password] and "language", "system" properties will be implicitly defined.

How is this going?  ...Found out that StrongBox is an candidate for me to change to (Like the Iphone app): Use KeepasXC for on mac and pc, but doesnt support Url override like Keepass do. Im working with it and uses all kinds of browser and browser profiles, so optimalt and a killer feature in Strongbox would be able to spesify both the browser type and profile you want for that url saved.

**Comment by dan-el** [comment]
Bumping this one. Being able to use the URL field to launch other Apps than the default browser would be cool.

Usually on macOS if you have a custom URL scheme registered already you can simply open correctly formatted links using the Terminal with `open urlscheme://myurl/moreurl` similar to `open https://strongbox.com` which would fire up your default browser.

Maybe we can have Strongbox simply hand non-browser URLs over to macOS instead of trying to open them in the default browser? This would allow users to take care of the custom url scheme on the OS level for starters and doesn't sound like too much work to get implemented into Strongbox.

**Comment by strongbox-mark** [comment]
Might be a quick one - will investigate shortly...

**Comment by strongbox-mark** [comment]
@dan-el do you have an example of a non browser URL I could test with?

**Comment by georgesnow** [comment]
Are we taking like sftp:// ?

**Comment by dan-el** [comment]
Here are a few examples:
`open mailto:support@strongbox.com`
`open skype://01 2345678`
`open "maps://?q=Museums&sll=-100.0,30&sspn=145.0,145.0"`

**Comment by strongbox-mark** [comment]
Thanks @dan-el - I assume in the entry in Strongbox the URL would just be "scheme://..." not "open scheme://..."?

**Comment by dan-el** [comment]
Yes, correct.

Expected behaviour should look like this:
- I add a custom URL into the URL field - e.g. `skype://+43 1 2345678` (note: no double quotes should be needed to escape stuff)
- When I launch the URL from Strongbox I expect the same behaviour as if I typed the URL into Terminal with the leading `open` command and with the double quotes like so: `open "skype://+43 1 2345678"`

What happens if I do not have the URL scheme registered in my system? What about extra checks?
- In the above example I'd probably need Skype installed unless I registered the `skype` URL scheme myself (unlikely).
- Strongbox could attempt to quick check, whether the used URL scheme is registered in the system at all, and only pass the URL on to the system if so (see link above, also might need some more research to determine the best way to list all custom URL schemes)
- The user could set up an allow list of custom URL schemes in the Strongbox settings. This would probably also address security concerns regarding unexpected behaviour and typos in the URL field.
- If Strongbox ever registered its own URL scheme to open up specific entries that scheme should probably be on a hard coded block list to avoid looping I think.

**Comment by strongbox-mark** [comment]
Thanks @dan-el - that's great. I'll see what can be done.

**Comment by georgesnow** [comment]
I believe part of this is falls under NSWorkspace, which handles opening urls with options.

https://developer.apple.com/documentation/appkit/nsworkspace

**Comment by strongbox-mark** [comment]
Thanks @georgesnow - perhaps NSTask too

**Comment by georgesnow** [comment]
Maybe not very familiar  with NStask.

Just for reference
 Shuttle does URL opening/handling using NSworkspace. you can check out line 556- 571:

https://github.com/fitztrev/shuttle/blob/1080360d4e586935840836e4ac9c5b48a690b9f3/Shuttle/AppDelegate.m#L556

this method should use the default (or last) registered handler of a scheme. Maybe this too much detail, but if anyone is interested. My expectation would be my entry would just contain “sftp://blah” and if I clicked on it. Then default handler would open.

Example in terminal 

open “sftp://blah.local”

woukd use the default handler say it’s Fetch.

Then if you used

open -a Transmit “sftp://blah.local” 

this overrides the registered handler. And would use Transmit instead of fetch like the example above.

**Comment by Niko-CZ** [comment]
Hi Mark,
I have just updated to Version 1.15.2 (2999) and the custom URL launch by OS works perfectly! Thank you very much for this feature implementation. 
I bought PRO version, but also would like to ask - do you have donation option? I would like to support this project in future.
Also my suggestion is to put custom URL handling on strongboxsafe.com web-site as one of features. I would bet that this will attract automation geeks like me:)

Regards,
Nikolay

**Comment by dan-el** [comment]
The new feature works fine, but anytime I launch a URL (tested with the above Skype example) I also get to see a notification in Strongbox saying that the password of the entry was copied. Is this expected behaviour?

**Comment by strongbox-mark** [comment]
Thanks @Niko-CZ 

@dan-el - If you choose to Launch and Copy Password then you'll get that Toast Notification. You can also choose just to "Launch URL".

You can also turn off Toast Notifications if they're annoying. Or does that not work for you?

**Comment by strongbox-mark** [comment]
@Niko-CZ - I've added Custom URL Handling to the feature list now. Good idea. As to how to support the project probably just a regular old subscription is best but there are a couple of other ways mentioned in the README if you're feeling generous :).

I think I'll close this one out now.

**Comment by dan-el** [comment]
Hi @strongbox-mark ,

Please nevermind my question. I only looked at the two buttons next to the URL field. Of course there are more options in the shortcuts or the right-click menu. No idea how I could have missed that.

Thanks for the clarification 🙈
