### ISSUE TITLE
Privacy policy does not match reality

### ISSUE THREAD

**Issue by keepassium** [strongbox-password-safe/Strongbox#443]
*Disclaimer: I acknowledge having a personal interest in this issue. This might affect my interpretation of the listed policies. For transparency, I am writing this from the official KeePassium account.*

Strongbox' AppStore listing claims that "Data Not Collected". This does not seem to be the case. Here's why.

### Cloud SDKs

Apple's guide on [answering app privacy questions](https://developer.apple.com/app-store/app-privacy-details/#user-tracking) (highlights are mine):

> “Collect” refers to transmitting data off the device in a way that allows you and/**or your third-party partners** to access it for a period longer than what is necessary to service the transmitted request in real time.

> Examples of tracking include:
> <...>
> Placing a third-party SDK in your app that combines user data from your app with user data from other developers’ apps to target advertising or measure advertising efficiency, **even if you don’t use the SDK for these purposes**.

So developers are responsible for the used SDKs and a simple reference "check with Google" won't do here. We need to go deeper and check [Google APIs Terms of Service](https://developers.google.com/terms#a_google_privacy_policies):

> By using our APIs, Google may use submitted information in accordance with our [privacy policies](https://www.google.com/policies/privacy/).

They refer to the general Google privacy policy, so advertisement is certainly involved. I assume OneDrive and Dropbox SDKs are governed by similarly permissive terms.

### Favicon downloader 

Favicon downloader has an option to fetch favicons via Google API. In this case, Strongbox would share user-generated content (domain names of the URLs) with Google, which can use this information for advertisement.

### SFTP and WebDAV

Strongbox privacy policy [declares](https://web.archive.org/web/20201221131550/https://strongboxsafe.com/privacy/):

> As no personal information is collected, transmitted, or maintained by the Application, we do not share personal information with anyone.

When the user connects to SFTP or WebDAV service provider, Strongbox explicitly transmits (shares) user credentials to these services. In particular, this can include user email as a username. Sure, this is implied for most users. However, your privacy policy claims nothing like this ever happens.

---

So, in my interpretation, Strongbox collects the following [types of data](https://developer.apple.com/app-store/app-privacy-details/#data-type) (as defined by Apple):

- **WebDAV/SFTP credentials**: Contact Info - Email Address (Including but not limited to a hashed email address)
- **Domain names in favicon downloader**: User Content - Other User Content (Any other user-generated content)
- **OAuth tokens for cloud APIs**: Identifiers - User ID (Such as screen name, handle, account ID, assigned user ID, customer number, or other user- or account-level ID that can be used to identify a particular user or account.)

What is your view?

**Comment by strongbox-mark** [comment]
Hi Andrei, 

As you say, you have a direct interest here as the main commercial competitor to Strongbox and so it is very hard to see this kind of legalistic nitpicking as a good faith engagement. Writing this response is not how I wanted to spend any part of my day.

However, let me do my best to imagine that it came from someone who wasn't interested in pointlessly expending my time and energy. There are, of course, always differences of opinion and interpretation when it comes to these things. Our privacy policy is something we review periodically and on our last check we believe we had offered a thoroughly fair, honest and reasonable statement of our privacy practices. I believe that to still be the case. When we answered Apple's App Privacy questions we believe we answered everything honestly in line with their guidelines. We could not be more open about the issues you have raised and specifically go out of our way to deal with issues of cloud provider privacy, personal information privacy and transmission off the device of any kind here:

[How can I trust that Strongbox is not sending my passwords elsewhere or stealing them?](https://strongboxsafe.com/support/#reamaze#0#/kb/security-and-privacy/how-can-i-trust-that-strongbox-is-not-sending-my-passwords-elsewhere-or-stealing-them)

[What information is shared with Cloud Providers (e.g. Google Drive) by Strongbox?](https://strongboxsafe.com/support/#reamaze#0#/kb/security-and-privacy/what-information-is-store-by-cloud-providers)

[What possible network connections can Strongbox make?](https://strongboxsafe.com/support/#reamaze#0#/kb/security-and-privacy/what-possible-network-connections-can-strongbox-make)

This is because of the importance of such issues to our users. All of the the issues you raise are opt-in features. Of course you already know all of this so I don't want to spend too much time here. I think that one of the most obvious improvements that could be made is to add the above links to the privacy policy and spell it out more. I will add that to our internal backlog along with a more thorough review of privacy in general.

Personally, as a founder and dev I'm saddened and super disappointed to see this kind of petty political game playing. This is desperate and cynical trolling that I didn’t think I’d see from someone I regarded as a honest competitor. I'm sure we're both busy people and this sort of internet forum commentary isn't something I think indie devs should be burning a lot of time on. Privacy policies are important and ours is super clear, honest and straightforward. I stand by it and the linked articles above. Parsing out our interpretations of giant corporations' legal codes is neither fun, enlightening nor fruitful for us or our users. I am not a lawyer but I do my best and I seek help where I can. 

Finally, as one indie dev to another, let's compete out there in the market making the best product we can for our users, we both charge enough and so they deserve that. That way we all win and we personally get to work on the things we love. I would ask you now to refrain from commenting on Strongbox forums from your personal or business accounts as it's clearly done in (very) bad faith and I have no intention of wasting any more of my time. I’d rather be in XCode.

Regards,
-Mark

**Comment by keepassium** [comment]
> I would ask you now to refrain from commenting on Strongbox forums from your personal or business accounts

No problem. I believe your attack is not justified, so I will reply to it below and then see myself out. I would appreciate if you keep this issue — closed or otherwise — so I can refer to it in the future. Thanks.

-Andrei

---

Mark, it seems you take this way too personally. 

> However, let me do my best to imagine that it came from someone who wasn't interested in pointlessly expending my time and energy.

Someone who wanted to troll you would do so anonymously on Reddit (more impact). Someone who wanted to harm your sales would post this as an AppStore review. Instead, I identified myself, posted to your technical issue tracker, and spent two hours gathering arguments. Focused on the issue, steered clear of comparisons with *a competing app*. All for the doubtful benefit of distracting you for an hour and starting a war? 

From our previous contacts, you should know better than this. When I learned about your #74, I [reported](https://github.com/strongbox-password-safe/Strongbox/issues/74) it. When I found solution for #117, I [shared](https://github.com/strongbox-password-safe/Strongbox/issues/117#issuecomment-494976507) it with you. Do you remember who emailed you about your WHOIS info being public? You did not mind the help.

Now I question a privacy-related formality — and half of your *ad hominem* response attacks me rather than the issue. Sure, I know that privacy is a sensitive topic for us; any hint of doubt feels like a personal offense. But your reaction is way too extreme.

How could I raise the issue without being accused of evil intentions? Email it to you and get a dismissive response privately? Post it elsewhere? Post as a concerned user? Title it differently? I don't believe you would prefer to silence the issue altogether. But it does feel like you are shooting the messenger.

> All of the the issues you raise are opt-in features. 

According to Apple, opt-in features [must be declared](https://developer.apple.com/app-store/app-privacy-details/#additional-guidance) as well (highlights are mine):

> You collect different types of data from users depending on whether the user is a child, whether they are a free or paid user, **whether they opt in**, where they live, or for some other reason.
> **Please disclose all data collected from your app**, unless it meets all of the criteria outlined in the Optional Disclosure section.

Sure, you can call this 

> legalistic nitpicking

I call this respecting the rules to be transparent with your users. 

I respect your work and never implied any intentional wrongdoing. Apparently, you did not know that developers are responsible for the data shared by third party SDKs, including "opt in" features. A honest mistake, I also make them. But now you know and sticking to "it's fine" would be a conscious choice.

You cannot ~~have your cake and eat it~~ use Google SDK and declare "No Data Shared". At least, not in good faith anymore...
