### ISSUE TITLE
Store the TOTP credentials/settings in KeePass format only

### ISSUE THREAD

**Issue by Slummi** [strongbox-password-safe/Strongbox#471]
Strongbox stores the TOTP settings redundantly in various custom fields (e.g. otp, TimeOtp-Secret-Base32, TOTP Seed etc.), because the various plugins use different custom fields for OTPs. I would prefer to only save the data once in KeePass 2.47 format when setting up TOTP via Strongbox.

Would that be something for the advanced settings that the user can choose whether he wants to save the data only in KeePass 2.47 format or additionally in other formats for the other applications / plugins?

**Comment by strongbox-mark** [comment]
Yes, not a bad idea at all.

**Comment by strongbox-mark** [comment]
Hi @Slummi - This should be available for you now. There are 2 Advanced Preferences in App Preferences. You can turn off Legacy fields, and you can turn off the OTPAUTH URL in there.

**Comment by Slummi** [comment]
Hi @strongbox-mark,

thank you for implementing this. Now I can use Strongbox to setup TOTP without having to delete the redundant fields.

**Comment by ankrman** [comment]
Hi @strongbox-mark,

from time to time I'm doing an export from KeePass to Enpass (for my wife). I now found out that Enpass uses the legacy fields instead of "otp" so after the export the OTP codes are not generated in Enpass. 

Do you know of a quick way to add the legacy fields afterwards? I could of course copy the seed into the custom fields manually but hey...

Thanks in advance

**Comment by strongbox-mark** [comment]
Hrmmm, not sure I know of a quick way to do this. I think you're probably best just to leave the legacy fields on? Or if Enpass can scan QR Codes, then maybe long tap on the TOTP to show the QR Code and scan it with Enpass on the other device?
