### ISSUE TITLE
Can't sync when in Offline Mode

### ISSUE THREAD

**Issue by daletman** [strongbox-password-safe/Strongbox#492]
I've set my Database to `Always open offline` and this option says I can pull down to perform a sync. When I do that I get the Notification `Offline Mode - Database not refreshed`.

I'm using an iPhone XR with iOS 14.4.1 and Strongbox 1.52.10 Pro and sync via SFTP.

**Comment by shad0whawk** [comment]
I use OneDrive and tried the same setup and my database refreshes without any issues. Maybe it's an issue with using SFTP or your SFTP connection setup.

**Comment by daletman** [comment]
> I use OneDrive and tried the same setup and my database refreshes without any issues. Maybe it's an issue with using SFTP or your SFTP connection setup.

I tried opening the same setup not in offline mode and it works just fine and also pull down to refresh then works just fine. It only doesn’t work in offline mode

**Comment by strongbox-mark** [comment]
Yes, if you're inside a database the Pull down to refresh feature won't work. That's by design. I will look at disabling the Pull Down feature in this case to be extra explicit about it. Once you unlock a database in Offline mode, it is expected that it won't try to sync or connect out to the remote storage provider.

What the text says is that if you pull down to refresh on the "Databases List" you will get a sync. That should be working for you. If it's not please feel free to open/re-open another issue.
