### ISSUE TITLE
Duplicate entries in AutoFill results

### ISSUE THREAD

**Issue by azfar** [strongbox-password-safe/Strongbox#524]
I have an entry which has multiple URLS under custom attributes, precisely I am accessing amazon.com in browser and my entry has amazon.com and www.amazon.com. logically it should appear only 2 times at most in autofill result as rest of the URLs are not amazon.com but they are appearing 4 times. See attached.

<a href="https://ibb.co/jhQff6B"><img src="https://i.ibb.co/fMyFF1B/Screen-Shot-2021-05-31-at-3-40-02-PM.jpg" alt="Screen-Shot-2021-05-31-at-3-40-02-PM" border="0"></a>
<a href="https://ibb.co/K7kYvPf"><img src="https://i.ibb.co/Y8M6sC1/Screen-Shot-2021-05-31-at-3-58-15-PM.jpg" alt="Screen-Shot-2021-05-31-at-3-58-15-PM" border="0"></a>

**Comment by strongbox-mark** [comment]
That's definitely interesting, and sounds like it might be a bug. Thanks for raising. Will investigate. As you say should be max 2 occurrences.

**Comment by strongbox-mark** [comment]
Investigated this, it's a bit of a bug and will be fixed in the next release. Basically alternative URL custom fields are checked twice for URLs. If there's no scheme (http/https) component in them (as in your case), the first scan adds https, and the second scan by Apples Link Detector returns them as http. So you end up with

http://amazon.com
https://amazon.com
http://www.amazon.com
https://www.amazon.com

All of which the AutoFill system considers valid for suggestion on https://www.amazon.com, which I think is fair enough. The work around until the fix is to add an explicit scheme to your URLs. The fix, is just to scan alternative URLs once. Should be released in the coming weeks.

**Comment by azfar** [comment]
> Investigated this, it's a bit of a bug and will be fixed in the next release. Basically alternative URL custom fields are checked twice for URLs. If there's no scheme (http/https) component in them (as in your case), the first scan adds https, and the second scan by Apples Link Detector returns them as http. So you end up with
> 
> http://amazon.com
> https://amazon.com
> http://www.amazon.com
> https://www.amazon.com
> 
> All of which the AutoFill system considers valid for suggestion on https://www.amazon.com, which I think is fair enough. The work around until the fix is to add an explicit scheme to your URLs. The fix, is just to scan alternative URLs once. Should be released in the coming weeks.

Thanks for the suggestion, adjusting my entries to minimize the effect.

**Comment by georgesnow** [comment]
Ah ok I have been trying to figure out why I have so many duplicates in auto fill.

**Comment by strongbox-mark** [comment]
This is fixed now with the release of 1.52.23 :)
