### ISSUE TITLE
No contribution rule

### ISSUE THREAD

**Issue by rubenvitt** [strongbox-password-safe/Strongbox#534]
Hey, 

regarding your / Apples licensing rules, maybe the following helps, if you like:

https://cla-assistant.io

Bitwarden uses it as contribution requirement and is listed in the AppStore, too.

Thanks for building such a great product! 😍 got me from the first second...

**Comment by strongbox-mark** [comment]
Hi @rubenvitt - Thank you for the link and your very kind words. Really glad you like the app! 

I think I would still be leaning towards keeping the current contribution policy, purely because of the overhead of managing new contributors, and a certain sense of personal ownership/pride in the work. It's quite a complex code base, which would take weeks/months to become familiar with, even if contributors were excellent and experienced Objective-C coders.
