### ISSUE TITLE
No autofill with Safari Technology Preview

### ISSUE THREAD

**Issue by rubenvitt** [strongbox-password-safe/Strongbox#535]
With Safari Technology Preview I'm unable to autofill the items on my Mac.
If I choose an element, nothing happens.

**Comment by strongbox-mark** [comment]
Thanks for the report @rubenvitt - There's been one other report of this from another user, but I haven't had the time to investigate. Usually these issues are fixed before a production release, so it often isn't worth expending resources on these things. Just one of the issues in running beta software I'm afraid. 

Let's keep this open, to track and so that others are aware of the issue.

**Comment by strongbox-mark** [comment]
Just an update, this looks to be an issue with the Technology Preview Safari. Anyone experiencing this should file a bug with Apple. This is the best way to get this fixed quickly.

For Monterey users, you should be able to install the older regular version of Safari which should work for you.

**Comment by strongbox-mark** [comment]
I believe this is all ok now @rubenvitt in the latest Safari release?
