### ISSUE TITLE
No going back from "Biometrics unavailable"

### ISSUE THREAD

**Issue by vbergl** [strongbox-password-safe/Strongbox#536]
I have enabled Face ID in Strongbox on my iPhone X. Unfortunately Face Id is broken on that iPhone now.
When Strongbox starts it displays "Biometrics unavailable"  and doesn't allow me to do anything (like disabling Face id in Strongbox)
I thought that I will copy Strongbox db from iPhone to Mac but the Files section doesn't show any files.
I am afraid that removing Strongbox from iPhone will remove db as well.
Is there any way of recovering the db ?
And yes I think that there should be way how to disable Face ID in Strongbox, so this to me qualifies as bug.

**Comment by strongbox-mark** [comment]
Hi there, sounds less than ideal, and yes, if your database is local only then removing Strongbox from the phone will remove that database. 

Is it local only? Do you have a recent backup?

Also, just to be clear, this only relates to the App Lock feature.

What happens when you enable Face ID on your Phone?

What would your suggested fix be in this situation (and how would you prevent a malicious user from taking advantage)?

**Comment by vbergl** [comment]
db is local only, but I do have backup on Mac. 
Yes it's app lock feature.
The only way how to enable Face ID is to have it repaired or buying new phone (I will end up doing this eventually, but I don't want to do it now). The lenses for Face ID are probably broken, I've spent long time to fix it without any luck.
Since Face ID can be changed with iPhone passcode it doesn't introduce any new door to attacks to provide app unlock to be also done with passcode. Although I don't know if this is viable solution.
I thought copying db from "iTunes" would be a way out, but obviously for security reasons the db is hidden.

**Comment by strongbox-mark** [comment]
OK, good that you have a backup. If you take a backup of your broken iPhone (and you have allowed Strongbox to include local databases in backups (you will have been asked about this)) then the local database will be in the iTunes backup too even if the database is hidden from the "Files" app. So if you can do a backup now, the latest database would be included in the backup and you could restore to another phone.

What happens if you enable Face ID and then proceed to fail the Face ID authentication on App Lock? Because, by default Strongbox allows a fallback to the device passcode for App Lock when Face ID fails. Or did you turn off that fallaback?

**Comment by vbergl** [comment]
I cannot enable Face ID it just responds with Face ID Unavailable and that's it. I had to reset it because it was not working but reset made it even worse.
Strongbox just displays "Biometrics unavailable" and doesn't allow me to do anything other than press OK, which means initiaa unlock screen.

**Comment by georgesnow** [comment]
I thought there was an option to uninstall/delete but  leave local copy of the data. Then you can reinstall strongbox from the App Store as I believe the p list settings would be defaults. I had this issue when Touch ID broke on my phone

**Comment by strongbox-mark** [comment]
It sounds like you have device passcode fallback switched off for App Lock, so you won't be able to get past the App Lock I'm afraid. Given that this feature is available, and on by default, I'm not sure there's much that can be done here from a dev standpoint...
