### ISSUE TITLE
Edit Order of KeePass Entries

### ISSUE THREAD

**Issue by mmcguill** [strongbox-password-safe/Strongbox#56]
Allow a user to change the order of entries (supported by KeePass but not by Password Safe at the moment)

**Comment by shad0whawk** [comment]
I see that you added an “A-Z” (ascending) sort option in 1.22.2. I’d like to suggest that maybe add an option to automatically switch the button to a “Z-A” (descending) if the ascending sort order has already been selected within that instance of the program. Just a thought to add some flexibility to the sorting. I don’t think you should add another button because then the interface becomes too crowded.

**Comment by mmcguill** [comment]
Yes, not a bad idea.

**Comment by shad0whawk** [comment]
Thanks!

**Comment by mmcguill** [comment]
Should be done for you in iOS 1.23.0. Will leave open for Mac App work.

**Comment by shad0whawk** [comment]
Another thought on the sorting...

The sort order already accounts for sorting ascending and descending by entry title, but I think it would be useful to be able to optionally sort the entry order by creation and/or modification date in ascending and descending order.

**Comment by mmcguill** [comment]
Hi @shad0whawk, would you want this in the iOS app or just in the Mac app, seems a little niche for the mobile app and might make the UI a little clunky, but I'm open to it as a feature...

**Comment by shad0whawk** [comment]
Well definitely don’t want to introduce any clunkiness into the UI. My thought was to replace the A-Z / Z-A button with a submenu that contains options for sorting and possible future related UI options.

**Comment by strongbox-mark** [comment]
This is now also available on macOS...
