### ISSUE TITLE
Feature request: Add multiple storage accounts of the same type (i.e. Onedrive + Onedrive for Business

### ISSUE THREAD

**Issue by enricogasparini** [strongbox-password-safe/Strongbox#562]
As the subject says, would be possible adding support for having two different storage accounts from the same provider? 

**Use case**
A user has two different keepass databases to use at the same time, hosted in different accounts from the same provider.
For example, a personal keepass database on the OneDrive account and a work keepass database on the OneDrive for Business account.

**Current behaviour**
The user can't add the two Onedrive databases a the same time to Strongbox

**Suggested/Expected behaviour**
It should be possible adding both the storage providers and connect to the two databases a the same time

**Comment by strongbox-mark** [comment]
Hi @enricogasparini - Have you seen this help article:

https://strongbox.reamaze.com/kb/storage-providers-third-party/i-want-to-access-two-different-databases-on-two-different-dropbox-slash-google-slash-onedrive-eg-personal-or-work-accounts

You can do this by leveraging iOS Files and our native OneDrive support.

**Comment by enricogasparini** [comment]
You're right, sorry for not noticing this before posting :)
Sadly (I've learn it the hard way with another app) iOS has the habit of breaking the associations to files provided by the iOS files app after each update.. so I don't find this kind of integration too reliable. You might end up editing an entry and finding the app unable to update the original kdbx file.. or am I wrong?

**Comment by strongbox-mark** [comment]
That can definitely happen with iOS Files :( unfortunately, it's not super reliable. Are you using KeePass or KeePassXC on Mac/Windows? There are "Safe Save" settings that can break the iOS Files linkage, turning these settings off should improve things with iOS Files.

**Comment by enricogasparini** [comment]
I'm using KeepassXC on Windows, I'll definitely try changing that setting :)

Thanks

**Comment by strongbox-mark** [comment]
Yes, let us know how it goes. The setting is here: 

KeePassXC
Settings > General > Basic Settings > File Management > Safely save database files > Switch OFF

**Comment by georgesnow** [comment]
This appears to happen with MacPass as well. But there doesn't seem to be an option for that setting. Although, when you say break what does that mean? I noticed file reference is out of date and won't update to reflect what iOS files.app and one drive displays. They will say "Today" last modified but strongbox will have the previous or older date of lat modification and won't reflect changes

**Comment by strongbox-mark** [comment]
Yes, that's what I mean by "break", the reference becomes stale and often you will need to "Re-locate" the file in iOS Files for Strongbox.

**Comment by strongbox-mark** [comment]
When I say Relocate I use that word, I use it because Strongbox pops up a message asking you to relocate the file when it detects a broken reference. You may be experiencing another condition and that's probably down to how the OneDrive app integrates with iOS Files. 

It's OneDrive you're experiencing this with on iOS, right?

**Comment by georgesnow** [comment]
Yeah I don't get a message. It's just I notice the file is outdated because the password I updated is reflected if I open on a Mac with a KeePassium client (macpass, strongbox etc...) and the modified date is when I changed the password.

And I can confirm on iOS in the Files.app and OneDrive it's the newer modified date. But strongbox shows the old one even after deleting it from strongbox. And trying all 3 ways (files.app open in, OneDrive open in strongbox "local copy", or strongbox itself and using files option (not one drive handler).

**Comment by strongbox-mark** [comment]
Hi @georgesnow, Could you open iOS Settings > OneDrive > Clear Account Settings. This might clear any caches in OneDrive. You will need to re-login to OneDrive and re-add your databases in Strongbox. Would be interested to hear if this helps.

**Comment by strongbox-mark** [comment]
Hi @enricogasparini , @georgesnow - As of 1.55.2, we have a new integration with OneDrive using the MSAL API. This means you can login with different accounts for different databases using the same native OneDrive, instead of having to use the Files app.

You will probably need to re-add any OneDrive databases also, to pickup this latest code path. Please feel free to re-open if this is still an issue.
