### ISSUE TITLE
1.54.3 crashes to homescreen when opening settings

### ISSUE THREAD

**Issue by ankrman** [strongbox-password-safe/Strongbox#565]
- iOS 15.1.1
- iPhone 12 mini
- lang: de

Can't provide a crash log, ironically this is in preferences ;)

**Comment by juanbretti** [comment]
# Bug Description
Settings crashes the application

# Steps To Reproduce
1. Open the database
2. Close the database
3. Press on the "wheel" to open the system settings 
4. The application crashes and closes. No warning message.

# Expected Behavior
Expected the application to open the "applications settings".

# Environment
* Strongbox Version: 1.54.3
* OS: iOS 15.1
* Phone: iPhone 11 Pro
* System language: English
* Connected vía WiFi to Internet

**Comment by strongbox-mark** [comment]
Hi @juanbretti @ankrman - thanks for the report... Fix on the way and with Apple now for review.

**Comment by strongbox-mark** [comment]
Fix should be available for you now @juanbretti @ankrman

**Comment by ankrman** [comment]
Confirmed, it's working again. Thanks 👍🏼

**Comment by juanbretti** [comment]
> Fix should be available for you now @juanbretti @ankrman

Works, this _bug_ can be closed.
