### ISSUE TITLE
Hide on copy 

### ISSUE THREAD

**Issue by georgesnow** [strongbox-password-safe/Strongbox#633]
there is minimize on copy, but if there was toggle option between minimize or hide strongbox.

**Comment by igorzamyslov** [comment]
Would also appreciate the "Hide" option instead of "Minimize".
The reason being: 
- minimizing an application doesn't remove the focus from the window, so the fact that the application is hidden from the screen, doesn't change the fact that one has to manually switch back to the previous application.
- hiding an application, moves the focus back to the previous app, which would be very convenient :)

**Comment by strongbox-mark** [comment]
Hi @georgesnow, just to let you know, this should be available for you now with 1.58.5. Let me know if there are any issues.
