### ISSUE TITLE
iCloud Sync conflict summary

### ISSUE THREAD

**Issue by PingSoup** [strongbox-password-safe/Strongbox#637]
When there is database Sync Conflict, it would be extremely useful to be able to see a quick summary of changes made so that one can make a correct decision to either merge or pick one data base over the other. Currently, I have to rely on my memory, which is not very reliable, or make a blind guess.
Apologies if this feature already exist and I don't know it. In that case, I would be grateful some directions on how to use it.
Regard,

**Comment by strongbox-mark** [comment]
Hi, yes, you should be able to see a "Diff" or "Compare" view. What do you see when you get a sync conflict? Do you not see any option to 'Compare'? Could you send a screen shot of what you are seeing?

**Comment by PingSoup** [comment]
Thank you for the reply,
Sorry if I caused a bit of confusion. What I meant to say was that it would be good to be able to compare when there is "version conflict", similar to options provided when there is "sync conflict" between remote and local DBs. 
In case of "version conflict" one is only given a choice between what DB to pick - see attached. It would be nice to have a "compare option" so that one can see what  is being added when I pick one or the other version
![Strongbox_version conflict](https://user-images.githubusercontent.com/85657770/182219207-38420b60-32b1-4a8f-8634-77d362c75cb8.PNG)

**Comment by strongbox-mark** [comment]
Oh, that's much better. So this is iCloud specific issue only, and we have plans to try to improve this in the future. Other providers do offer the ability to view changes when there is a sync conflict.

**Comment by PingSoup** [comment]
Thank you, Mark. Will eagerly wait for iCloud enhancement for this.

**Comment by strongbox-mark** [comment]
Similar to #549,  @PingSoup, with 1.60.5, you can export any version on the versions list so that you can later merge them yourself manually. You would simply import them into Strongbox and select Compare & Merge.

Unfortunately because of the way iCloud conflict versions works, it's technically quite difficult to fit it into our standard merge workflow. On top of that, we no longer recommend using iCloud because we just don't have tight control over the read/write process. We do provide an alternative now that doesn't require third parties like OneDrive or Dropbox, etc. This is our new "Strongbox Sync" which you can read about here:

https://strongboxsafe.com/support/#reamaze#0#/kb/sync/strongbox-sync

We recommend you switch over to Strongbox Sync if you can...

These factors mean that some kind of automatic support for merging conflicts is very unlikely to see the light of day in the short to medium term. Just want to keep you updated.
