### ISSUE TITLE
Support Passkeys

### ISSUE THREAD

**Issue by nagromc** [strongbox-password-safe/Strongbox#651]
Please consider adding support for [Passkeys](https://developer.apple.com/passkeys/) that will be available in macOS Ventura.

**Comment by Horschig** [comment]
Passkeys seem to be starting off now. Any progress on this? I would love to sync my passkeys with my own server and my strongbox app.

**Comment by strongbox-mark** [comment]
No updates just yet, will update here when we have some news.

**Comment by alcroito** [comment]
Hi, I tried out the passkey support in the latest iOS version with github.com (preview feature).
I had created 2 passkeys, then deleted them, and then created a third one one.
My database only contains the third one now, the old ones i removed from recycle bin entirely.
But now when i try to login with a passkey, i get offered 3 identical looking passkeys, of which only one works.
Looks like either iOS has remembered the old ones somehow, or strongbox is reporting passkeys that don't exist anymore.
Is there a way to reset the offered passkeys? Like i said, the DB contains only one.
Restating the phone did not help.

**Comment by strongbox-mark** [comment]
Hi @alcroito - I think this is probably unrelated to Passkeys. Do you have more than one AutoFill enabled database? If so, you will see stale entries in the QuickType suggestions list. This is unfortunately due to the AutoFill API design.

If you ca, disable AutoFill on all but one of your databases and this will remove stale entries. If this isn't possible you can disable Strongbox globally for AutoFill, then switch it back on. This will clear the QuickType suggestions list, and then when you open each database, only fresh entries will be added to the suggestions list.

Long story about the stale entries, but not super easy to fix

**Comment by strongbox-mark** [comment]
Closing this one out now, we've got Passkey support looking good

**Comment by skmgoldin** [comment]
I've been using Strongbox's passkey support heavily on both iOS and MacOS, and am very happy with it!
