### ISSUE TITLE
UX: Create New Record --> Create New Account

### ISSUE THREAD

**Issue by elharo** [strongbox-password-safe/Strongbox#691]
# Bug Description

The tooltip on the key icon says "Create New Record"

Describe the bug/issue you have.

This has two problems:

1. The corresponding menu item is "Create New Entry" (not record)
2.  "Record" is not a term understood by non-developer end users. "Entry" is only marginally better.

Both should probably be "Create New Account". Perhaps someone can think of a better word here than "Account" but "Record" should definitely be changed. 

# Steps To Reproduce
Mouse over the key

# Expected Behavior

# Screenshots

![image](https://user-images.githubusercontent.com/1005544/177161871-8556daa6-400d-42b6-8105-b48cb19a6cea.png)

# Environment

Mac OS X 10.14

* Strongbox Version: 
* OS: 

1.17.1

* [link1]()
* [link2]()
* [link3]()

# Task Relationships

This bug:
* Is caused by: 
* Relates to: 
* Depends on:

**Comment by dan-el** [comment]
"Entry" sounds like the way to go to me. After all it's a database entry. Also not all entries store account information, some are just notes or attached documents etc.
My 2 cents.

**Comment by strongbox-mark** [comment]
Hi @elharo - Entry would be the right term here, but it looks like you're using the old "deprecated" UI, and not the NextGen UI. This is probably because you're running macOS older than 10.15? We (unfortunately) have 2 macOS UIs, one of them is deprecated, we keep it around for users on old versions of macOS.

The new ("NextGen") UI shouldn't have this issue. We won't be fixing cosmetic issues in the old UI. Hope that makes sense.
