### ISSUE TITLE
Associated Domains - Adjust Microsoft Domains

### ISSUE THREAD

**Issue by dan-el** [strongbox-password-safe/Strongbox#732]
Microsoft knows two types of accounts: Corporate (Office365, Azure, etc.) and Personal (live.com)

One can login with any type of account at https://login.microsoftonline.com - personal accounts will be redirected to https://login.live.com
One **cannot** login with a corporate account at https://login.live.com - the page will show an error message "That Microsoft account doesn't exist"

I have accounts in my database with the URL set to https://login.microsoftonline.com (corporate Office365 accounts) which are being offered at https://login.live.com when the "Associated Domains" feature is turned on. Those accounts won't work on that login form as described above.

**My request:**
Separate the Microsoft associated domains list into two lists. One for Microsoft's personal login service (aka live.com) and one for Microsoft's corporate services.

I tried different login forms with corporate and personal accounts:
- personal domains: live.com, skype.com, hotmail.com, microsoft.com
- working for both types: onenote.com, office.com, microsoftonline.com
- corporate domains: n/a

**Comment by strongbox-mark** [comment]
Hey @dan-el - That's interesting and I can see your point. Thing is we take this list from the Apple Password Quirks list. I think it would be best from a maintenance point of view if we could get it fixed upstream, or hear arguments for why it is as it is. Could you raise that issue there perhaps:

https://github.com/apple/password-manager-resources#shared-credentials

Mostly because I don't want to create my own fork of this database and manage updates/maintenance.

**Comment by dan-el** [comment]
Raised the issue with them as suggested
https://github.com/apple/password-manager-resources/issues/719
