### ISSUE TITLE
Feature request: Support for iOS TOTP integration

### ISSUE THREAD

**Issue by fwcd** [strongbox-password-safe/Strongbox#750]
iOS seems to have an API for integrating third-party 2FA/authenticator/TOTP apps with autofill and it would be really cool if Strongbox could support this:

![image](https://github.com/strongbox-password-safe/Strongbox/assets/30873659/4d820df9-2f8d-431a-bead-7d3e99b53ba8)

**Comment by strongbox-mark** [comment]
We've got this on our list :)

**Comment by ghqe** [comment]
Cool.

**Comment by ghqe** [comment]
> We've got this on our list :)

How is the progress of this feature?

**Comment by strongbox-mark** [comment]
No news just yet. Are you seeing the need for this very often? Could you describe how you see this working or a recent experience where it would have been useful.

**Comment by mietzen** [comment]
It would be really interesting if it was working properly.

I only managed to get the autofill part working using Apple Keychain. No matter which Authenticator App I configure for codes in the passwort option:

![IMG_7230](https://github.com/strongbox-password-safe/Strongbox/assets/31704359/6c1b1b38-35ab-41f2-a6ba-254cc8444fa9)

I only get the "Open in" part:

![IMG_7231](https://github.com/strongbox-password-safe/Strongbox/assets/31704359/10633d74-3070-4b7c-bfc4-1a725c148987)

but not the fill part:

![IMG_7229](https://github.com/strongbox-password-safe/Strongbox/assets/31704359/395f8a2d-083f-4f07-a0d1-791ccd2e2d81)

Here a working example with keychain:

![IMG_7232](https://github.com/strongbox-password-safe/Strongbox/assets/31704359/3f86bab4-efb0-4f9f-ae6b-a97323d4147e)

If the "auto fill" part is not possible (Which might well be since seamingly no one got it working), I personally don't see the need for it since I rarely setup 2FA from my phone.

**Comment by strongbox-mark** [comment]
@mietzen 

- There's no native iOS/macOS API to fill TOTPs which is why no one is doing it
- Strongbox copies the TOTP code to the clipboard after AutoFilling
- Strongbox has a TOTP List view

**Comment by strongbox-mark** [comment]
This is now (finally) available with 1.60.17 on both iOS and macOS. Please open new issues if you find any.
